[build]
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.
  # If not set, defaults to the root directory.
  base = "project/"

  publish = ".dist"
  command = "pnpm run build || ( npm install pnpm && pnpm run build )"
  
[build.environment]
    NPM_FLAGS="--prefix=/dev/null"